# Generated by Django 5.1.7 on 2025-04-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_experience_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
